/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The name a new room is created under.  Creation is idempotent on the name: an existing name returns that room instead of failing.
 *
 * @param name The name to create. Printable ASCII, 1–64 characters; matched case-insensitively against the rooms that already exist.
 */
@Serializable

data class CreateRoomRequest (

    /* The name to create. Printable ASCII, 1–64 characters; matched case-insensitively against the rooms that already exist. */
    @SerialName(value = "name")
    val name: kotlin.String

) {


}

