/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * What a successful login yields: the bearer token every authenticated request carries.
 *
 * @param expiresAt When the token stops being accepted. There are no refresh tokens — a client logs in again.
 * @param token The JWT to send as `Authorization: Bearer <token>`. Opaque to clients: they carry it, they do not parse it.
 */
@Serializable

data class LoginResponse (

    /* When the token stops being accepted. There are no refresh tokens — a client logs in again. */
    @SerialName(value = "expires_at")
    val expiresAt: kotlin.Long,

    /* The JWT to send as `Authorization: Bearer <token>`. Opaque to clients: they carry it, they do not parse it. */
    @SerialName(value = "token")
    val token: kotlin.String

) {


}

