/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The credentials an existing account is authenticated with.
 *
 * @param password The password in the clear, verified against the stored hash.
 * @param username The registered name to log in as.
 */
@Serializable

data class LoginRequest (

    /* The password in the clear, verified against the stored hash. */
    @SerialName(value = "password")
    val password: kotlin.String,

    /* The registered name to log in as. */
    @SerialName(value = "username")
    val username: kotlin.String

) {


}

