/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model

import com.anapaya.chat.client.model.Message

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A page of a room's messages.
 *
 * @param messages The page, **always oldest-first**, whichever cursor asked for it.  A page shorter than the requested `limit` means the client has reached the end it was walking towards: the present when polling forwards, the start of history when loading older messages. A full page means more might be waiting — ask again immediately.
 */
@Serializable

data class MessagesResponse (

    /* The page, **always oldest-first**, whichever cursor asked for it.  A page shorter than the requested `limit` means the client has reached the end it was walking towards: the present when polling forwards, the start of history when loading older messages. A full page means more might be waiting — ask again immediately. */
    @SerialName(value = "messages")
    val messages: kotlin.collections.List<Message>

) {


}

