/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One message in a room.  Messages are append-only: never edited, never deleted.
 *
 * @param body The message text.
 * @param postedAt When the server accepted the message.
 * @param seq The message's position in the sequence, and the cursor used to fetch around it.
 * @param username The account that posted it.
 */
@Serializable

data class Message (

    /* The message text. */
    @SerialName(value = "body")
    val body: kotlin.String,

    /* When the server accepted the message. */
    @SerialName(value = "posted_at")
    val postedAt: kotlin.Long,

    /* The message's position in the sequence, and the cursor used to fetch around it. */
    @SerialName(value = "seq")
    val seq: kotlin.Long,

    /* The account that posted it. */
    @SerialName(value = "username")
    val username: kotlin.String

) {


}

