/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Where a posted message landed.  A client does *not* advance its poll cursor to this `seq` — a message with a lower `seq` may still be waiting to be polled. The cursor only ever follows what polling actually delivered.
 *
 * @param postedAt When the server accepted the message. Server time — a client's own clock never appears on the wire.
 * @param seq The `seq` the server assigned to the new message.
 */
@Serializable

data class PostMessageResponse (

    /* When the server accepted the message. Server time — a client's own clock never appears on the wire. */
    @SerialName(value = "posted_at")
    val postedAt: kotlin.Long,

    /* The `seq` the server assigned to the new message. */
    @SerialName(value = "seq")
    val seq: kotlin.Long

) {


}

