/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The text of a message being posted.
 *
 * @param body The message text. UTF-8, at most the server's `max_message_bytes` when encoded — see [`ServerInfo`](super::ServerInfo).
 */
@Serializable

data class PostMessageRequest (

    /* The message text. UTF-8, at most the server's `max_message_bytes` when encoded — see [`ServerInfo`](super::ServerInfo). */
    @SerialName(value = "body")
    val body: kotlin.String

) {


}

