/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The credentials a new account is created with.  The username is the account's permanent identity — the name messages are attributed to. There is no rename, no password change, and no password reset.
 *
 * @param password The password in the clear — the connection's TLS is what protects it. The server keeps only a KDF hash.
 * @param username The name to register. UTF-8, 1–32 characters, no control characters; compared case-insensitively against the names already taken.
 */
@Serializable

data class RegisterRequest (

    /* The password in the clear — the connection's TLS is what protects it. The server keeps only a KDF hash. */
    @SerialName(value = "password")
    val password: kotlin.String,

    /* The name to register. UTF-8, 1–32 characters, no control characters; compared case-insensitively against the names already taken. */
    @SerialName(value = "username")
    val username: kotlin.String

) {


}

