/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A room.  Every user belongs to every room: there is no membership, no joining, and no private rooms. A room named `lobby` always exists.
 *
 * @param id The room's identifier, used in the message paths.
 * @param latestSeq The `seq` of the newest message in the room, or `0` while it has none.  Comparing it against the newest `seq` a client has read is what drives an unread badge, so one listing covers every room at once. Not a count: `seq` is server-wide (see [`Seq`]).
 * @param name The room's display name. Printable ASCII, 1–64 characters; unique case-insensitively.
 */
@Serializable

data class Room (

    /* The room's identifier, used in the message paths. */
    @SerialName(value = "id")
    val id: kotlin.Long,

    /* The `seq` of the newest message in the room, or `0` while it has none.  Comparing it against the newest `seq` a client has read is what drives an unread badge, so one listing covers every room at once. Not a count: `seq` is server-wide (see [`Seq`]). */
    @SerialName(value = "latest_seq")
    val latestSeq: kotlin.Long,

    /* The room's display name. Printable ASCII, 1–64 characters; unique case-insensitively. */
    @SerialName(value = "name")
    val name: kotlin.String

) {


}

