/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.anapaya.chat.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Everything about the server a client may want to show or adapt to. Needs no token, so a client can read it before anyone logs in.
 *
 * @param maxAccounts How many accounts the server registers before it starts rejecting registrations.
 * @param maxMessageBytes The largest message body the server accepts, in bytes of UTF-8.
 * @param maxRooms How many rooms the server creates before it starts rejecting new ones.
 * @param tokenValiditySeconds How long a token stays valid after it is issued.
 * @param version The server build's version, as in its `Cargo.toml`.
 * @param isdAs The SCION ISD-AS the server is reachable in, or `null` when it is serving over plain TCP in development mode.
 */
@Serializable

data class ServerInfo (

    /* How many accounts the server registers before it starts rejecting registrations. */
    @SerialName(value = "max_accounts")
    val maxAccounts: kotlin.Int,

    /* The largest message body the server accepts, in bytes of UTF-8. */
    @SerialName(value = "max_message_bytes")
    val maxMessageBytes: kotlin.Int,

    /* How many rooms the server creates before it starts rejecting new ones. */
    @SerialName(value = "max_rooms")
    val maxRooms: kotlin.Int,

    /* How long a token stays valid after it is issued. */
    @SerialName(value = "token_validity_seconds")
    val tokenValiditySeconds: kotlin.Int,

    /* The server build's version, as in its `Cargo.toml`. */
    @SerialName(value = "version")
    val version: kotlin.String,

    /* The SCION ISD-AS the server is reachable in, or `null` when it is serving over plain TCP in development mode. */
    @SerialName(value = "isd_as")
    val isdAs: kotlin.String? = null

) {


}

