[workspace]
resolver = "2"

members = [
    "crates/chat-core",
    "crates/chat-server",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Anapaya & contributors"]
license = "Apache-2.0"
repository = "https://github.com/anapaya/scion-sdk-chat"

[workspace.dependencies]
async-trait = "0.1"
chat-core = { path = "crates/chat-core" }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.9", default-features = false, features = [
    "macros",
    "runtime-tokio",
    "sqlite",
] }
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt"] }
utoipa = "5.4"

[workspace.lints.clippy]
mem_forget = "deny"

[workspace.lints.rust]
missing_docs = "warn"

[profile.ci]
inherits = "dev"    # https://doc.rust-lang.org/cargo/reference/profiles.html#dev
incremental = false # Disable incremental compilation to allow caching dependencies
