//
// CreateRoomRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The name a new room is created under.  Creation is idempotent on the name: an existing name returns that room instead of failing. */
public struct CreateRoomRequest: Sendable, Codable, Hashable {

    /** The name to create. Printable ASCII, 1–64 characters; matched case-insensitively against the rooms that already exist. */
    public var name: String

    public init(name: String) {
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
    }
}

