//
// Health.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The body of a liveness check. */
public struct Health: Sendable, Codable, Hashable {

    /** Always `ok`; the status code carries the answer. */
    public var status: String

    public init(status: String) {
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
    }
}

