//
// LoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** What a successful login yields: the bearer token every authenticated request carries. */
public struct LoginResponse: Sendable, Codable, Hashable {

    public static let expiresAtRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** When the token stops being accepted. There are no refresh tokens — a client logs in again. */
    public var expiresAt: Int64
    /** The JWT to send as `Authorization: Bearer <token>`. Opaque to clients: they carry it, they do not parse it. */
    public var token: String

    public init(expiresAt: Int64, token: String) {
        self.expiresAt = expiresAt
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expiresAt = "expires_at"
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(token, forKey: .token)
    }
}

