//
// LoginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The credentials an existing account is authenticated with. */
public struct LoginRequest: Sendable, Codable, Hashable {

    /** The password in the clear, verified against the stored hash. */
    public var password: String
    /** The registered name to log in as. */
    public var username: String

    public init(password: String, username: String) {
        self.password = password
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(password, forKey: .password)
        try container.encode(username, forKey: .username)
    }
}

