//
// MessagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A page of a room&#39;s messages. */
public struct MessagesResponse: Sendable, Codable, Hashable {

    /** The page, **always oldest-first**, whichever cursor asked for it.  A page shorter than the requested `limit` means the client has reached the end it was walking towards: the present when polling forwards, the start of history when loading older messages. A full page means more might be waiting — ask again immediately. */
    public var messages: [Message]

    public init(messages: [Message]) {
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messages, forKey: .messages)
    }
}

