//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One message in a room.  Messages are append-only: never edited, never deleted. */
public struct Message: Sendable, Codable, Hashable {

    public static let postedAtRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let seqRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** The message text. */
    public var body: String
    /** When the server accepted the message. */
    public var postedAt: Int64
    /** The message's position in the sequence, and the cursor used to fetch around it. */
    public var seq: Int64
    /** The account that posted it. */
    public var username: String

    public init(body: String, postedAt: Int64, seq: Int64, username: String) {
        self.body = body
        self.postedAt = postedAt
        self.seq = seq
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case postedAt = "posted_at"
        case seq
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
        try container.encode(postedAt, forKey: .postedAt)
        try container.encode(seq, forKey: .seq)
        try container.encode(username, forKey: .username)
    }
}

