//
// PostMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The text of a message being posted. */
public struct PostMessageRequest: Sendable, Codable, Hashable {

    /** The message text. UTF-8, at most the server's `max_message_bytes` when encoded — see [`ServerInfo`](super::ServerInfo). */
    public var body: String

    public init(body: String) {
        self.body = body
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
    }
}

