//
// PostMessageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Where a posted message landed.  A client does *not* advance its poll cursor to this &#x60;seq&#x60; — a message with a lower &#x60;seq&#x60; may still be waiting to be polled. The cursor only ever follows what polling actually delivered. */
public struct PostMessageResponse: Sendable, Codable, Hashable {

    public static let postedAtRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let seqRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** When the server accepted the message. Server time — a client's own clock never appears on the wire. */
    public var postedAt: Int64
    /** The `seq` the server assigned to the new message. */
    public var seq: Int64

    public init(postedAt: Int64, seq: Int64) {
        self.postedAt = postedAt
        self.seq = seq
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case postedAt = "posted_at"
        case seq
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(postedAt, forKey: .postedAt)
        try container.encode(seq, forKey: .seq)
    }
}

