//
// RegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The credentials a new account is created with.  The username is the account&#39;s permanent identity — the name messages are attributed to. There is no rename, no password change, and no password reset. */
public struct RegisterRequest: Sendable, Codable, Hashable {

    /** The password in the clear — the connection's TLS is what protects it. The server keeps only a KDF hash. */
    public var password: String
    /** The name to register. UTF-8, 1–32 characters, no control characters; compared case-insensitively against the names already taken. */
    public var username: String

    public init(password: String, username: String) {
        self.password = password
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(password, forKey: .password)
        try container.encode(username, forKey: .username)
    }
}

