//
// RoomsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Every room on the server. */
public struct RoomsResponse: Sendable, Codable, Hashable {

    /** All rooms. Never empty: `lobby` is always present. */
    public var rooms: [Room]

    public init(rooms: [Room]) {
        self.rooms = rooms
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rooms
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rooms, forKey: .rooms)
    }
}

