//
// Room.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A room.  Every user belongs to every room: there is no membership, no joining, and no private rooms. A room named &#x60;lobby&#x60; always exists. */
public struct Room: Sendable, Codable, Hashable {

    public static let idRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let latestSeqRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** The room's identifier, used in the message paths. */
    public var id: Int64
    /** The `seq` of the newest message in the room, or `0` while it has none.  Comparing it against the newest `seq` a client has read is what drives an unread badge, so one listing covers every room at once. Not a count: `seq` is server-wide (see [`Seq`]). */
    public var latestSeq: Int64
    /** The room's display name. Printable ASCII, 1–64 characters; unique case-insensitively. */
    public var name: String

    public init(id: Int64, latestSeq: Int64, name: String) {
        self.id = id
        self.latestSeq = latestSeq
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case latestSeq = "latest_seq"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(latestSeq, forKey: .latestSeq)
        try container.encode(name, forKey: .name)
    }
}


extension Room: Identifiable {}
