//
// ServerInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Everything about the server a client may want to show or adapt to. Needs no token, so a client can read it before anyone logs in. */
public struct ServerInfo: Sendable, Codable, Hashable {

    public static let maxAccountsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let maxMessageBytesRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let maxRoomsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let tokenValiditySecondsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** The SCION ISD-AS the server is reachable in, or `null` when it is serving over plain TCP in development mode. */
    public var isdAs: String?
    /** How many accounts the server registers before it starts rejecting registrations. */
    public var maxAccounts: Int
    /** The largest message body the server accepts, in bytes of UTF-8. */
    public var maxMessageBytes: Int
    /** How many rooms the server creates before it starts rejecting new ones. */
    public var maxRooms: Int
    /** How long a token stays valid after it is issued. */
    public var tokenValiditySeconds: Int
    /** The server build's version, as in its `Cargo.toml`. */
    public var version: String

    public init(isdAs: String? = nil, maxAccounts: Int, maxMessageBytes: Int, maxRooms: Int, tokenValiditySeconds: Int, version: String) {
        self.isdAs = isdAs
        self.maxAccounts = maxAccounts
        self.maxMessageBytes = maxMessageBytes
        self.maxRooms = maxRooms
        self.tokenValiditySeconds = tokenValiditySeconds
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isdAs = "isd_as"
        case maxAccounts = "max_accounts"
        case maxMessageBytes = "max_message_bytes"
        case maxRooms = "max_rooms"
        case tokenValiditySeconds = "token_validity_seconds"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isdAs, forKey: .isdAs)
        try container.encode(maxAccounts, forKey: .maxAccounts)
        try container.encode(maxMessageBytes, forKey: .maxMessageBytes)
        try container.encode(maxRooms, forKey: .maxRooms)
        try container.encode(tokenValiditySeconds, forKey: .tokenValiditySeconds)
        try container.encode(version, forKey: .version)
    }
}

